sudo: required
language: bash
env:
  global:
  - IMAGE_NAME=gableroux/unity3d:2018.3.14f1
  - BUILD_NAME=Expedition13
  - secure: "X3wBDGnOM3UZ7JfRUKRCn/Mbo71xzH413NeBsQyWj0MUz+kxWgtaorWECu1mcC+Wr8ytYYKkZb5vPB6c5LPkU84gJjMfON1NZ4H3T5DYpvWiRJGNgt5n7waCE7ty36G8J3t5XDPkJUTrQMFsitN5MLW95ODcgy4ij8/g0ks40FUURgM3wWb01Ug0Y1VvaWjtVwIGxf7QdKTW63bwX17pC8IpDi8OtR5k2wlVoLh/4pzxPclmKGienT4MLAuU/hf4m3LIcmr60/uP9yCatnTBZ5YWVkqQxq1O/EVGa7gTyzCAtCb8Zrmuc53wNGQkPflOg9yV0OxQ4XJT2p8CB6EBKkDkBkBV57C12XxDn17oc+omRhRhjvRAoSRIJyYGqwmIMtuBlWYv6qGGgR95/Z0amXca5zJIE2luwrczcS6oPkRLMDdFb6R+xX+zKc7HHwjK8t054o8Db0lJv9/EBXALMlI3GCgorGgbt6tYHp+Rq+3/89osebI8TsS2nkc4jdIeT/m+YBUwIE1xrYEjOOdbhgOUu5sVvLd9jQ78QiVB0g31rH1VQdiQbxcC9d48RhMrzeDYZz8RXSd3AsByy2ouP0Sg5gPahODMJxLrjXmayML4KZ6Os1vgdTLmoY7ZFiwYKQKDtMYA9k1h+I3wjsQFR+fvFcZpDtPN/BzgazjNAgc="
services:
- docker
before_install:
- echo $super_secret_password | gpg --passphrase-fd 0 Unity_v2018.x.ulf.gpg
- export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
- rm Unity_v2018.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  # - stage: test
  #   script: "chmod +x ./Travis/docker_test.sh && ./Travis/docker_test.sh"
  #   env: TEST_PLATFORM=editmode
  #   addons:
  #     artifacts:
  #       target_paths:
  #       - "$(pwd)/$TEST_PLATFORM-results.xml"
  # - stage: test
  #   script: "chmod +x ./Travis/docker_test.sh && ./Travis/docker_test.sh"
  #   env: TEST_PLATFORM=playmode
  #   addons:
  #     artifacts:
  #       target_paths:
  #       - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64
    script:
      - "chmod +x ./Travis/docker_build.sh && ./Travis/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r ${BUILD_TARGET}.zip ./${BUILD_TARGET}/"
  - stage: build
    env: BUILD_TARGET=StandaloneOSX
    script:
      - "chmod +x ./Travis/docker_build.sh && ./Travis/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r ${BUILD_TARGET}.zip ./${BUILD_TARGET}/"
  - stage: build
    env: BUILD_TARGET=StandaloneWindows64
    script:
      - "chmod +x ./Travis/docker_build.sh &&./Travis/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r ${BUILD_TARGET}.zip ./${BUILD_TARGET}/"
deploy:
  provider: releases
  api_key:
    secure: 0Y6m90vygoLALmWWFFLBKbRHU74hj+OTbTZrVC45RB9u600SvTxMpvTpwUq5tkLPHbY4oZc7QfDHekhRTyhGJIRU5lEqHTGwpdy7SRoi41LaVAT8B7r5Z0RLgU9zE+zRvcmqBr8JC76B8liWUhgnv/pj/7PnYiqIXlpAfbX7TlSDv0WbYvWK7/uBee6UszYyiIC/1RGPxVWxKP1BKSORV+TU7u0F3aFrpW57BYvCiRO51NS7zTkCBGQrqxKzsKyM5EC/tzLoyw0cwz+s0FslRC6EkQcQCua3XXJcMSRQSlO6YcGfYWx6krUA+lMvf9IWSHxBzeUflAKmJx4KpPZN+6Yo3c6DJk3MK/TR4rxQneGMTgbzmO0hW97VuY2TWoqEBvvEYaVcP6nPJ2UPacf5avDhxBD+9wVNzgd7eZKWVxJJpn9fyn4D60TPnoVUifnbf8ufhEPc2JGy/GjDcBksrz27zIUlbZxeiHmYUhvP570qlDkoj7MbUfyOGlmIYHPHBA6hYcgovAE9Blfy97ZcZDAn7xs0XbkiZ2y6bMGhFOGg6jQj6Q/9rykVvVMNxKoaVo+rtOeIUeq8nIg6sWBWz7jpr41cikXmpGGGU7q0L/UxnPeoD+zAfaHSlt6MYmBYed/mOzwejqHqYFfDOLibFO/hc/6KXgRz/6loNIWB6TE=
  file: "${BUILD_TARGET}.zip"
  skip_cleanup: true
  # draft: true
  name: Experimental Build $TRAVIS_TAG $(date +%Y-%m-%d)
  body: There will be bugs!
  prerelease: true
  on:
    tags: true