sudo: required
language: bash
env:
  global:
  - IMAGE_NAME=gableroux/unity3d:2018.3.14f1
  - BUILD_NAME=Unitystation
  - secure: "X3wBDGnOM3UZ7JfRUKRCn/Mbo71xzH413NeBsQyWj0MUz+kxWgtaorWECu1mcC+Wr8ytYYKkZb5vPB6c5LPkU84gJjMfON1NZ4H3T5DYpvWiRJGNgt5n7waCE7ty36G8J3t5XDPkJUTrQMFsitN5MLW95ODcgy4ij8/g0ks40FUURgM3wWb01Ug0Y1VvaWjtVwIGxf7QdKTW63bwX17pC8IpDi8OtR5k2wlVoLh/4pzxPclmKGienT4MLAuU/hf4m3LIcmr60/uP9yCatnTBZ5YWVkqQxq1O/EVGa7gTyzCAtCb8Zrmuc53wNGQkPflOg9yV0OxQ4XJT2p8CB6EBKkDkBkBV57C12XxDn17oc+omRhRhjvRAoSRIJyYGqwmIMtuBlWYv6qGGgR95/Z0amXca5zJIE2luwrczcS6oPkRLMDdFb6R+xX+zKc7HHwjK8t054o8Db0lJv9/EBXALMlI3GCgorGgbt6tYHp+Rq+3/89osebI8TsS2nkc4jdIeT/m+YBUwIE1xrYEjOOdbhgOUu5sVvLd9jQ78QiVB0g31rH1VQdiQbxcC9d48RhMrzeDYZz8RXSd3AsByy2ouP0Sg5gPahODMJxLrjXmayML4KZ6Os1vgdTLmoY7ZFiwYKQKDtMYA9k1h+I3wjsQFR+fvFcZpDtPN/BzgazjNAgc="
services:
- docker
before_install:
- echo $super_secret_password | gpg --passphrase-fd 0 Unity_v2018.x.ulf.gpg
- export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
- rm Unity_v2018.x.ulf
- docker pull $IMAGE_NAME
jobs:
  include:
  # - stage: test
  #   script: "chmod +x ./Travis/docker_test.sh && ./Travis/docker_test.sh"
  #   env: TEST_PLATFORM=editmode
  #   addons:
  #     artifacts:
  #       target_paths:
  #       - "$(pwd)/$TEST_PLATFORM-results.xml"
  # - stage: test
  #   script: "chmod +x ./Travis/docker_test.sh && ./Travis/docker_test.sh"
  #   env: TEST_PLATFORM=playmode
  #   addons:
  #     artifacts:
  #       target_paths:
  #       - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64
    script:
      - "chmod +x ./Travis/docker_build.sh && ./Travis/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r ${BUILD_TARGET}.zip ./${BUILD_TARGET}/"
  - stage: build
    env: BUILD_TARGET=StandaloneOSX
    script:
      - "chmod +x ./Travis/docker_build.sh && ./Travis/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r ${BUILD_TARGET}.zip ./${BUILD_TARGET}/"
  - stage: build
    env: BUILD_TARGET=StandaloneWindows64
    script:
      - "chmod +x ./Travis/docker_build.sh &&./Travis/docker_build.sh"
      - "sudo chmod -R 777 ./Builds/"
      - "cd ./Builds/"
      - "zip -r ${BUILD_TARGET}.zip ./${BUILD_TARGET}/"
deploy:
  provider: releases
  api_key:
    secure: H1ELkzF5U81lBUsOqWX4pVGvE4oNvUuOtc1cIliunp3+BMSjUMNMcIoZvsVdbrlDaTV9AuGVEZw1mydaw7T7KpEp2L7RpgI1XcAR6qM28mFNO6vqUAtYzmo89MeXtKu1DWqowHqALbI2ML5K9Y7E+oi7Mov8pwOBAle7bZTS6nZrupr3LDI7C+0CNDUyxBztxWYfOSQ+r7NtMAd1yVCfbGqKFHJ6fQC912xyLqlqVXMhpgWlglvUfpGMUCn0/4OtJLinrWnJ+LbmzdV5kyOwlV5eJ+Jrur6ipFvZ6zBwjoJ0jbVddIoTAimI9qDkjKfZnArCDwTKcrCip2slUqX83EXtLDBO1fUejaE1/OfEUvJ/VETv2d3hkYKjOnAlfQMPKcy35Hk5ksUpfMi7yE0hHqm5rGbomUsmDneNYoSJFbGhBNJQ94Mu+CKcFS4GBnSlkyln+8NWnY7VmAbX5cV0sa4WevcoQSLnEBVJAE2bJg7Z+bUIssG89qzjx4UfIbqlAIlC7HYhm8mnajqSdGH0T8tgqoXJ6AsvGq6y2JCCukQVyG0CPaMhy3M7WxBIwWs0WmxefBuMEfH14LESxC/1JghLDVzWYhZLlm5Vbd3YCA8rAV1z5n55ZHfB3/FWpkcMbwRMxEaKSHEJ6c8CyEKOXnqvu4NxYUB7hkB6I95n1xI=
  file: "${BUILD_TARGET}.zip"
  skip_cleanup: true
  # draft: true
  name: Experimental Build $TRAVIS_TAG $(date +%Y-%m-%d)
  body: There will be bugs!
  prerelease: true
  on:
    tags: true